### PR TITLE
Add an out-of-scope playbook

### PR DESCRIPTION
**Pull request by jacobian**
Specify what to do about out-of-scope reports, with a bit of commentary.

### CODE REVIEW

**Review by commit-dkp — APPROVED** [review]
It's possible for the H1 URL to be out of sync with the policy in GitHub. Maybe don't include the H1 URL?  Also, was `handling-out-of-scope-reports.md` supposed to be an empty file?

**Comment by jacobian** [comment]
@commit-dkp what the heck, my computer ate that file apparently. Yes, there was supposed to be content there :(

**Comment by konklone** [comment]
:+1: on the text I can see, but yeah, I guess ping the PR again when you've restored the 0-byte file. I'm sorry for your loss. :(

**Comment by commit-dkp** [comment]
I think unless @jacobian is going to come back with a restored `handling-out-of-scope-reports.md`, this PR can be closed.

**Review by adborden — APPROVED** [review]

**Comment by adborden** [comment]
Should I just delete the empty file, since it's not referenced anywhere?

**Pull request merged**
